In [98]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
data science is leading tenchnology
"""

In [99]:
len(faqs)

5164

We will generating text here just like ChatGPT.
supervised learning model
we give above text as training data(input)
The main challenge here to make input and output data from this text

In [100]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [101]:
tokenizer = Tokenizer()

In [102]:
tokenizer.fit_on_texts([faqs])
#fit_on_texts method of the Tokenizer class from TensorFlow's Keras module. 
#It fits the tokenizer on the provided text data

In [103]:
tokenizer.word_index
#uh would see every words has got one number

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'is': 5,
 'a': 6,
 'of': 7,
 'have': 8,
 'will': 9,
 'can': 10,
 'what': 11,
 'course': 12,
 'program': 13,
 'in': 14,
 'for': 15,
 'all': 16,
 'sessions': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'this': 21,
 'if': 22,
 'am': 23,
 'pay': 24,
 'payment': 25,
 'make': 26,
 'we': 27,
 'do': 28,
 'data': 29,
 'subscription': 30,
 'where': 31,
 'rs': 32,
 'so': 33,
 'campusx': 34,
 'session': 35,
 'our': 36,
 'paid': 37,
 'join': 38,
 'able': 39,
 'your': 40,
 'website': 41,
 'placement': 42,
 'fee': 43,
 'science': 44,
 'monthly': 45,
 'month': 46,
 'not': 47,
 'get': 48,
 'yes': 49,
 'once': 50,
 'past': 51,
 'feb': 52,
 'assistance': 53,
 '7': 54,
 '5600': 55,
 'are': 56,
 'watch': 57,
 'google': 58,
 'by': 59,
 'com': 60,
 'mail': 61,
 'from': 62,
 'contact': 63,
 'us': 64,
 'at': 65,
 'or': 66,
 'doubt': 67,
 'mentorship': 68,
 'payments': 69,
 '799': 70,
 'total': 71,
 'duration': 72,
 'months': 73,
 'learning': 74,
 'case': 75,
 'here': 76,
 '

In [104]:
len(tokenizer.word_index)

284

In [105]:
for sentenses in faqs.split('\n'):
    print(sentenses)

About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a sessi

In [106]:
for sentence in faqs.split('\n'):
              tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
              print(tokenized_sentence)

[93, 1, 13]
[11, 5, 1, 12, 43, 15, 29, 44, 68, 13, 147, 148]
[1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4, 26, 45, 69, 7, 32, 70, 46]
[11, 5, 1, 71, 72, 7, 1, 12]
[1, 71, 72, 7, 1, 12, 5, 54, 73, 33, 1, 71, 12, 43, 149, 70, 54, 32, 55, 150]
[11, 5, 1, 96, 7, 1, 68, 13]
[27, 9, 19, 151, 1, 152, 153]
[97, 154]
[97, 155, 15, 29, 44]
[29, 156]
[157, 15, 29, 44]
[158, 15, 159, 74]
[98, 160]
[161, 98]
[162]
[75, 99]
[2, 10, 163, 1, 164, 96, 76, 77, 100, 34, 14, 165, 34, 29, 44, 68, 13, 166]
[9, 101, 74, 20, 102, 19, 6, 78, 7, 21, 13]
[103, 102, 20, 101, 74, 167, 56, 47, 6, 78, 7, 21, 168, 169]
[11, 22, 3, 104, 6, 105, 35, 9, 3, 48, 6, 106, 7, 1, 35]
[49, 16, 36, 17, 56, 170, 33, 107, 22, 2, 104, 6, 35, 2, 10, 171, 172, 20, 57, 1, 106]
[31, 10, 3, 173, 1, 108, 174]
[175, 21, 58, 176, 4, 79, 46, 59, 46, 109, 177, 7, 1, 12, 77, 178, 58, 60, 179, 180, 181, 182, 183, 184, 185]
[11, 5, 1, 109, 72, 7, 16, 1, 105, 17]
[186, 16, 1, 17, 187, 110, 188]
[11, 5, 1, 189, 190, 59, 1, 191, 192, 1, 17]
[193]
[111,

In [107]:
"my name is chetana"
["my","name"],["name","is"]

(['my', 'name'], ['name', 'is'])

In [108]:
input_sequences = []
for sentence in faqs.split('\n'):
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1,len(tokenized_sentence)):
        n_grams=tokenized_sentence[:i+1]
        input_sequences.append(n_grams)
        print(n_grams)


[93, 1]
[93, 1, 13]
[11, 5]
[11, 5, 1]
[11, 5, 1, 12]
[11, 5, 1, 12, 43]
[11, 5, 1, 12, 43, 15]
[11, 5, 1, 12, 43, 15, 29]
[11, 5, 1, 12, 43, 15, 29, 44]
[11, 5, 1, 12, 43, 15, 29, 44, 68]
[11, 5, 1, 12, 43, 15, 29, 44, 68, 13]
[11, 5, 1, 12, 43, 15, 29, 44, 68, 13, 147]
[11, 5, 1, 12, 43, 15, 29, 44, 68, 13, 147, 148]
[1, 12]
[1, 12, 94]
[1, 12, 94, 6]
[1, 12, 94, 6, 45]
[1, 12, 94, 6, 45, 30]
[1, 12, 94, 6, 45, 30, 95]
[1, 12, 94, 6, 45, 30, 95, 31]
[1, 12, 94, 6, 45, 30, 95, 31, 2]
[1, 12, 94, 6, 45, 30, 95, 31, 2, 8]
[1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4]
[1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4, 26]
[1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4, 26, 45]
[1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4, 26, 45, 69]
[1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4, 26, 45, 69, 7]
[1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4, 26, 45, 69, 7, 32]
[1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4, 26, 45, 69, 7, 32, 70]
[1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4, 26, 45, 69, 7, 32, 70, 46]
[11, 5]
[11, 5, 1]
[11, 5, 1, 71]
[11, 5, 1, 

In [109]:
input_sequences  #we have only input data which has different input sizes


[[93, 1],
 [93, 1, 13],
 [11, 5],
 [11, 5, 1],
 [11, 5, 1, 12],
 [11, 5, 1, 12, 43],
 [11, 5, 1, 12, 43, 15],
 [11, 5, 1, 12, 43, 15, 29],
 [11, 5, 1, 12, 43, 15, 29, 44],
 [11, 5, 1, 12, 43, 15, 29, 44, 68],
 [11, 5, 1, 12, 43, 15, 29, 44, 68, 13],
 [11, 5, 1, 12, 43, 15, 29, 44, 68, 13, 147],
 [11, 5, 1, 12, 43, 15, 29, 44, 68, 13, 147, 148],
 [1, 12],
 [1, 12, 94],
 [1, 12, 94, 6],
 [1, 12, 94, 6, 45],
 [1, 12, 94, 6, 45, 30],
 [1, 12, 94, 6, 45, 30, 95],
 [1, 12, 94, 6, 45, 30, 95, 31],
 [1, 12, 94, 6, 45, 30, 95, 31, 2],
 [1, 12, 94, 6, 45, 30, 95, 31, 2, 8],
 [1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4],
 [1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4, 26],
 [1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4, 26, 45],
 [1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4, 26, 45, 69],
 [1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4, 26, 45, 69, 7],
 [1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4, 26, 45, 69, 7, 32],
 [1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4, 26, 45, 69, 7, 32, 70],
 [1, 12, 94, 6, 45, 30, 95, 31, 2, 8, 4, 26, 45, 69, 7

In [110]:
#Ideally when we do supervised ml taksk we need same size of inputs ,so we have to do zerto padding
# for that we will find max length of input 

In [111]:
max_len = max([len(x) for x in input_sequences])#List comprehension

In [112]:
max_len

57

In [113]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [114]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,  93,   1,  13],
       [  0,   0,   0, ...,   0,  11,   5],
       ...,
       [  0,   0,   0, ...,  29,  44,   5],
       [  0,   0,   0, ...,  44,   5, 283],
       [  0,   0,   0, ...,   5, 283, 284]])

In [115]:
X = padded_input_sequences[:,:-1]

In [116]:
X

array([[  0,   0,   0, ...,   0,   0,  93],
       [  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,   0,   0,  11],
       ...,
       [  0,   0,   0, ...,   0,  29,  44],
       [  0,   0,   0, ...,  29,  44,   5],
       [  0,   0,   0, ...,  44,   5, 283]])

In [117]:
y = padded_input_sequences[:,-1]

In [118]:
X.shape

(867, 56)

In [119]:
y.shape

(867,)

In [120]:
y

array([  1,  13,   5,   1,  12,  43,  15,  29,  44,  68,  13, 147, 148,
        12,  94,   6,  45,  30,  95,  31,   2,   8,   4,  26,  45,  69,
         7,  32,  70,  46,   5,   1,  71,  72,   7,   1,  12,  71,  72,
         7,   1,  12,   5,  54,  73,  33,   1,  71,  12,  43, 149,  70,
        54,  32,  55, 150,   5,   1,  96,   7,   1,  68,  13,   9,  19,
       151,   1, 152, 153, 154, 155,  15,  29,  44, 156,  15,  29,  44,
        15, 159,  74, 160,  98,  99,  10, 163,   1, 164,  96,  76,  77,
       100,  34,  14, 165,  34,  29,  44,  68,  13, 166, 101,  74,  20,
       102,  19,   6,  78,   7,  21,  13, 102,  20, 101,  74, 167,  56,
        47,   6,  78,   7,  21, 168, 169,  22,   3, 104,   6, 105,  35,
         9,   3,  48,   6, 106,   7,   1,  35,  16,  36,  17,  56, 170,
        33, 107,  22,   2, 104,   6,  35,   2,  10, 171, 172,  20,  57,
         1, 106,  10,   3, 173,   1, 108, 174,  21,  58, 176,   4,  79,
        46,  59,  46, 109, 177,   7,   1,  12,  77, 178,  58,  6

In [124]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=285)

In [125]:
y.shape

(867, 285)

In [126]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [131]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model = Sequential()
model.add(Embedding(285, 100, input_length=56))
model.add(LSTM(150, return_sequences=True))  # Set return_sequences=True to feed the output to the next LSTM layer
model.add(LSTM(150))
model.add(Dense(285, activation='softmax'))

# Compile the model and specify loss function, optimizer, etc.
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Print model summary to check the architecture and parameter count
model.summary()


Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 56, 100)           28500     
                                                                 
 lstm_10 (LSTM)              (None, 56, 150)           150600    
                                                                 
 lstm_11 (LSTM)              (None, 150)               180600    
                                                                 
 dense_3 (Dense)             (None, 285)               43035     
                                                                 
Total params: 402735 (1.54 MB)
Trainable params: 402735 (1.54 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [132]:
model.fit(X,y,epochs=100)

Epoch 1/100
28/28 [==============================] - 7s 71ms/step - loss: 5.4379 - accuracy: 0.0577
Epoch 2/100
28/28 [==============================] - 2s 72ms/step - loss: 5.0992 - accuracy: 0.0704
Epoch 3/100
28/28 [==============================] - 2s 67ms/step - loss: 5.0476 - accuracy: 0.0773
Epoch 4/100
28/28 [==============================] - 2s 65ms/step - loss: 5.0298 - accuracy: 0.0773
Epoch 5/100
28/28 [==============================] - 2s 66ms/step - loss: 5.0186 - accuracy: 0.0773
Epoch 6/100
28/28 [==============================] - 2s 72ms/step - loss: 5.0191 - accuracy: 0.0773
Epoch 7/100
28/28 [==============================] - 2s 75ms/step - loss: 5.0114 - accuracy: 0.0773
Epoch 8/100
28/28 [==============================] - 2s 78ms/step - loss: 5.0008 - accuracy: 0.0773
Epoch 9/100
28/28 [==============================] - 2s 71ms/step - loss: 4.9858 - accuracy: 0.0773
Epoch 10/100
28/28 [==============================] - 2s 67ms/step - loss: 4.9331 - accuracy: 0.0773

28/28 [==============================] - 2s 72ms/step - loss: 0.3231 - accuracy: 0.9331
Epoch 83/100
28/28 [==============================] - 2s 73ms/step - loss: 0.3182 - accuracy: 0.9400
Epoch 84/100
28/28 [==============================] - 2s 75ms/step - loss: 0.3135 - accuracy: 0.9389
Epoch 85/100
28/28 [==============================] - 2s 72ms/step - loss: 0.3046 - accuracy: 0.9354
Epoch 86/100
28/28 [==============================] - 2s 68ms/step - loss: 0.2981 - accuracy: 0.9389
Epoch 87/100
28/28 [==============================] - 2s 68ms/step - loss: 0.2935 - accuracy: 0.9354
Epoch 88/100
28/28 [==============================] - 2s 69ms/step - loss: 0.2840 - accuracy: 0.9389
Epoch 89/100
28/28 [==============================] - 2s 67ms/step - loss: 0.2739 - accuracy: 0.9354
Epoch 90/100
28/28 [==============================] - 2s 67ms/step - loss: 0.2623 - accuracy: 0.9423
Epoch 91/100
28/28 [==============================] - 2s 65ms/step - loss: 0.2567 - accuracy: 0.9446
Epo

In [133]:
tokenizer.word_index

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'is': 5,
 'a': 6,
 'of': 7,
 'have': 8,
 'will': 9,
 'can': 10,
 'what': 11,
 'course': 12,
 'program': 13,
 'in': 14,
 'for': 15,
 'all': 16,
 'sessions': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'this': 21,
 'if': 22,
 'am': 23,
 'pay': 24,
 'payment': 25,
 'make': 26,
 'we': 27,
 'do': 28,
 'data': 29,
 'subscription': 30,
 'where': 31,
 'rs': 32,
 'so': 33,
 'campusx': 34,
 'session': 35,
 'our': 36,
 'paid': 37,
 'join': 38,
 'able': 39,
 'your': 40,
 'website': 41,
 'placement': 42,
 'fee': 43,
 'science': 44,
 'monthly': 45,
 'month': 46,
 'not': 47,
 'get': 48,
 'yes': 49,
 'once': 50,
 'past': 51,
 'feb': 52,
 'assistance': 53,
 '7': 54,
 '5600': 55,
 'are': 56,
 'watch': 57,
 'google': 58,
 'by': 59,
 'com': 60,
 'mail': 61,
 'from': 62,
 'contact': 63,
 'us': 64,
 'at': 65,
 'or': 66,
 'doubt': 67,
 'mentorship': 68,
 'payments': 69,
 '799': 70,
 'total': 71,
 'duration': 72,
 'months': 73,
 'learning': 74,
 'case': 75,
 'here': 76,
 '

In [134]:
import time
import numpy as np
text = "data science is"

for i in range(5):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))
  #print(padded_token_text)

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 [==============================] - 1s 978ms/step
data science is leading
1/1 [==============================] - 0s 37ms/step
data science is leading tenchnology
1/1 [==============================] - 0s 37ms/step
data science is leading tenchnology read
1/1 [==============================] - 0s 37ms/step
data science is leading tenchnology read carefully
1/1 [==============================] - 0s 36ms/step
data science is leading tenchnology read carefully you
